### ISSUE TITLE
Using custom maps as background

### ISSUE THREAD

**Issue by DanielLenz** [nasa-lambda/cmb_footprint#4]
I've tried to use a custom map for the background, similar to what has been commented in the various examples.

```python

import numpy as np
import matplotlib.pyplot as plt
import healpy as hp

import os
import sys
separator = os.sep
fullpath = os.getcwd().split(separator)
source_path = separator.join(fullpath[0:-2])
sys.path.append(source_path)

from cmb_footprint import footprint

if __name__ == '__main__':

    background_map = np.arange(hp.nside2npix(256))

    fp = footprint.SurveyStack(
        background_map, config='../footprint.cfg',
        coord_bg='G', coord_plot='G',
        min=background_map.min(), max=background_map.max())

    fp.superimpose_survey('BOSS-LSS-RANDOM2', color='green')
    plt.show()
```

That produces the following output:

![figure_1](https://user-images.githubusercontent.com/7532391/34891451-7ab5dd40-f78a-11e7-873d-520201c84828.png)

Any help is greatly appreciated, I really enjoyed playing around with the package!

**Comment by njmiller** [comment]
This is because, by default, the code takes the logarithm of the background map (log=True) and then plots the color scale linearly on this new map. Since you are inputting a minimum value of 0, this causes issues when setting the minimum value to log(0). Right now, you can either set log=False or change the range of the background map/color scale.

**Comment by DanielLenz** [comment]
Major oversight on my part, thanks for clarifying!
